# Use the official Node.js 14 image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which your application will run
EXPOSE 8080

# Command to run your application
CMD ["node", "index.js"]


# gcloud run deploy instance-20240422-221509 --image gcr.io/se422/your-image-name --platform managed